=== crawljax/crawljax/core/src/main/resources/com/crawljax/core/plugin/descriptor/jaxb/plugin-descriptor.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
            xmlns:jxb="http://java.sun.com/xml/ns/jaxb"
            jxb:version="2.0">

	<xs:element name="plugin-descriptor">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="name" type="xs:string"/>
				<xs:element name="description" type="xs:string"/>
				<xs:element name="crawljax-versions" type="version-list"/>
				<xs:element name="parameters" type="parameter-list" minOccurs="0"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>

	<xs:complexType name="version-list">
		<xs:sequence>
			<xs:element name="version" type="xs:string" maxOccurs="unbounded"/>
		</xs:sequence>
	</xs:complexType>

	<xs:complexType name="parameter-list">
		<xs:sequence>
			<xs:element name="parameter" type="parameter" maxOccurs="unbounded"/>
		</xs:sequence>
	</xs:complexType>

	<xs:complexType name="parameter">
		<xs:sequence>
			<xs:element name="id" type="xs:string"/>
			<xs:element name="display-name" type="xs:string"/>
			<xs:element name="type">
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:enumeration value="textbox"/>
						<xs:enumeration value="checkbox"/>
						<xs:enumeration value="select"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:element>
			<xs:element name="options" type="option-list" minOccurs="0"/>
		</xs:sequence>
	</xs:complexType>

	<xs:complexType name="option-list">
		<xs:sequence>
			<xs:element name="option" maxOccurs="unbounded">
				<xs:complexType>
					<xs:sequence>
						<xs:element name="name" type="xs:string"/>
						<xs:element name="value" type="xs:string"/>
					</xs:sequence>
				</xs:complexType>
			</xs:element>
		</xs:sequence>
	</xs:complexType>

</xs:schema>

=== crawljax/crawljax/plugin-archetype/src/main/resources/archetype-resources/src/main/resources/plugin-descriptor.xml
<?xml version="1.0" encoding="UTF-8"?>
<plugin-descriptor xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
				   xsi:schemaLocation="https://raw.github.com/crawljax/crawljax/web-ui-plugin-support/core/src/main/resources/com/crawljax/core/plugin/jaxb/plugin-descriptor.xsd">
	<name>Sample Plugin</name>
	<description>Sample plugin to demonstrate basic plugin implementation</description>
	<crawljax-versions>
		<version>${project.version}</version>
	</crawljax-versions>
	<parameters>
		<parameter>
			<id>sample_textbox</id>
			<display-name>Sample Textbox</display-name>
			<type>textbox</type>
		</parameter>
		<parameter>
			<id>sample_checkbox</id>
			<display-name>Sample Checkbox</display-name>
			<type>checkbox</type>
		</parameter>
		<parameter>
			<id>sample_select</id>
			<display-name>Sample Select</display-name>
			<type>select</type>
			<options>
				<option>
					<name>Option 1</name>
					<value>1</value>
				</option>
				<option>
					<name>Option 2</name>
					<value>2</value>
				</option>
				<option>
					<name>Option 3</name>
					<value>3</value>
				</option>
			</options>
		</parameter>
	</parameters>
</plugin-descriptor>

=== crawljax/crawljax/plugins/test-plugin/src/main/resources/plugin-descriptor.xml
<?xml version="1.0" encoding="UTF-8"?>
<plugin-descriptor xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
				   xsi:schemaLocation="https://raw.github.com/crawljax/crawljax/web-ui-plugin-support/core/src/main/resources/com/crawljax/core/plugin/jaxb/plugin-descriptor.xsd">
	<name>Test Plugin</name>
	<description>A plugin to use for testing</description>
	<crawljax-versions>
		<version>${project.version}</version>
	</crawljax-versions>
	<parameters>
		<parameter>
			<id>test_textbox</id>
			<display-name>Test Textbox</display-name>
			<type>textbox</type>
		</parameter>
		<parameter>
			<id>test_checkbox</id>
			<display-name>Test Checkbox</display-name>
			<type>checkbox</type>
		</parameter>
		<parameter>
			<id>test_select</id>
			<display-name>Test Select</display-name>
			<type>select</type>
			<options>
				<option>
					<name>Option 1</name>
					<value>1</value>
				</option>
				<option>
					<name>Option 2</name>
					<value>2</value>
				</option>
				<option>
					<name>Option 3</name>
					<value>3</value>
				</option>
			</options>
		</parameter>
	</parameters>
</plugin-descriptor>
